// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: zmk/mouse_gesture/mouse_gesture.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "zmk.mouse_gesture";

export const Direction = {
  DIRECTION_UNSPECIFIED: 0,
  DIRECTION_UP: 1,
  DIRECTION_DOWN: 2,
  DIRECTION_LEFT: 4,
  DIRECTION_RIGHT: 8,
  UNRECOGNIZED: -1,
} as const;

export type Direction = typeof Direction[keyof typeof Direction];

export namespace Direction {
  export type DIRECTION_UNSPECIFIED = typeof Direction.DIRECTION_UNSPECIFIED;
  export type DIRECTION_UP = typeof Direction.DIRECTION_UP;
  export type DIRECTION_DOWN = typeof Direction.DIRECTION_DOWN;
  export type DIRECTION_LEFT = typeof Direction.DIRECTION_LEFT;
  export type DIRECTION_RIGHT = typeof Direction.DIRECTION_RIGHT;
  export type UNRECOGNIZED = typeof Direction.UNRECOGNIZED;
}

export interface Binding {
  localId: number;
  param1: number;
  param2: number;
}

export interface Gesture {
  name: string;
  pattern: Direction[];
  bindings: Binding[];
}

export interface ActivationKey {
  name: string;
  position: number;
  layer: number;
  tappingTermMs: number;
  tap: Binding | undefined;
  up: Binding | undefined;
  down: Binding | undefined;
  left: Binding | undefined;
  right: Binding | undefined;
}

export interface Config {
  strokeSize: number;
  idleTimeoutMs: number;
  gestureCooldownMs: number;
  movementThreshold: number;
  eagerMode: boolean;
  alwaysActive: boolean;
  gestures: Gesture[];
  activationKeys: ActivationKey[];
}

export interface ListRequest {
}

export interface ListResponse {
  config: Config | undefined;
}

export interface SaveRequest {
  config: Config | undefined;
}

export interface SaveResponse {
}

export interface ResetRequest {
}

export interface ResetResponse {
  config: Config | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Request {
  list?: ListRequest | undefined;
  save?: SaveRequest | undefined;
  reset?: ResetRequest | undefined;
}

export interface Response {
  list?: ListResponse | undefined;
  save?: SaveResponse | undefined;
  reset?: ResetResponse | undefined;
  error?: ErrorResponse | undefined;
}

function createBaseBinding(): Binding {
  return { localId: 0, param1: 0, param2: 0 };
}

export const Binding: MessageFns<Binding> = {
  encode(message: Binding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.localId !== 0) {
      writer.uint32(8).uint32(message.localId);
    }
    if (message.param1 !== 0) {
      writer.uint32(16).uint32(message.param1);
    }
    if (message.param2 !== 0) {
      writer.uint32(24).uint32(message.param2);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Binding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.localId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.param1 = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.param2 = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Binding>): Binding {
    return Binding.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Binding>): Binding {
    const message = createBaseBinding();
    message.localId = object.localId ?? 0;
    message.param1 = object.param1 ?? 0;
    message.param2 = object.param2 ?? 0;
    return message;
  },
};

function createBaseGesture(): Gesture {
  return { name: "", pattern: [], bindings: [] };
}

export const Gesture: MessageFns<Gesture> = {
  encode(message: Gesture, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    writer.uint32(18).fork();
    for (const v of message.pattern) {
      writer.int32(v);
    }
    writer.join();
    for (const v of message.bindings) {
      Binding.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Gesture {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGesture();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.pattern.push(reader.int32() as any);

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.pattern.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bindings.push(Binding.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Gesture>): Gesture {
    return Gesture.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Gesture>): Gesture {
    const message = createBaseGesture();
    message.name = object.name ?? "";
    message.pattern = object.pattern?.map((e) => e) || [];
    message.bindings = object.bindings?.map((e) => Binding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseActivationKey(): ActivationKey {
  return {
    name: "",
    position: 0,
    layer: 0,
    tappingTermMs: 0,
    tap: undefined,
    up: undefined,
    down: undefined,
    left: undefined,
    right: undefined,
  };
}

export const ActivationKey: MessageFns<ActivationKey> = {
  encode(message: ActivationKey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.position !== 0) {
      writer.uint32(16).uint32(message.position);
    }
    if (message.layer !== 0) {
      writer.uint32(24).uint32(message.layer);
    }
    if (message.tappingTermMs !== 0) {
      writer.uint32(32).uint32(message.tappingTermMs);
    }
    if (message.tap !== undefined) {
      Binding.encode(message.tap, writer.uint32(42).fork()).join();
    }
    if (message.up !== undefined) {
      Binding.encode(message.up, writer.uint32(50).fork()).join();
    }
    if (message.down !== undefined) {
      Binding.encode(message.down, writer.uint32(58).fork()).join();
    }
    if (message.left !== undefined) {
      Binding.encode(message.left, writer.uint32(66).fork()).join();
    }
    if (message.right !== undefined) {
      Binding.encode(message.right, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActivationKey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActivationKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.position = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.layer = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.tappingTermMs = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tap = Binding.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.up = Binding.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.down = Binding.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.left = Binding.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.right = Binding.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ActivationKey>): ActivationKey {
    return ActivationKey.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ActivationKey>): ActivationKey {
    const message = createBaseActivationKey();
    message.name = object.name ?? "";
    message.position = object.position ?? 0;
    message.layer = object.layer ?? 0;
    message.tappingTermMs = object.tappingTermMs ?? 0;
    message.tap = (object.tap !== undefined && object.tap !== null) ? Binding.fromPartial(object.tap) : undefined;
    message.up = (object.up !== undefined && object.up !== null) ? Binding.fromPartial(object.up) : undefined;
    message.down = (object.down !== undefined && object.down !== null) ? Binding.fromPartial(object.down) : undefined;
    message.left = (object.left !== undefined && object.left !== null) ? Binding.fromPartial(object.left) : undefined;
    message.right = (object.right !== undefined && object.right !== null)
      ? Binding.fromPartial(object.right)
      : undefined;
    return message;
  },
};

function createBaseConfig(): Config {
  return {
    strokeSize: 0,
    idleTimeoutMs: 0,
    gestureCooldownMs: 0,
    movementThreshold: 0,
    eagerMode: false,
    alwaysActive: false,
    gestures: [],
    activationKeys: [],
  };
}

export const Config: MessageFns<Config> = {
  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.strokeSize !== 0) {
      writer.uint32(8).uint32(message.strokeSize);
    }
    if (message.idleTimeoutMs !== 0) {
      writer.uint32(16).uint32(message.idleTimeoutMs);
    }
    if (message.gestureCooldownMs !== 0) {
      writer.uint32(24).uint32(message.gestureCooldownMs);
    }
    if (message.movementThreshold !== 0) {
      writer.uint32(32).uint32(message.movementThreshold);
    }
    if (message.eagerMode !== false) {
      writer.uint32(40).bool(message.eagerMode);
    }
    if (message.alwaysActive !== false) {
      writer.uint32(48).bool(message.alwaysActive);
    }
    for (const v of message.gestures) {
      Gesture.encode(v!, writer.uint32(58).fork()).join();
    }
    for (const v of message.activationKeys) {
      ActivationKey.encode(v!, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.strokeSize = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.idleTimeoutMs = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.gestureCooldownMs = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.movementThreshold = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.eagerMode = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.alwaysActive = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.gestures.push(Gesture.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.activationKeys.push(ActivationKey.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Config>): Config {
    return Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Config>): Config {
    const message = createBaseConfig();
    message.strokeSize = object.strokeSize ?? 0;
    message.idleTimeoutMs = object.idleTimeoutMs ?? 0;
    message.gestureCooldownMs = object.gestureCooldownMs ?? 0;
    message.movementThreshold = object.movementThreshold ?? 0;
    message.eagerMode = object.eagerMode ?? false;
    message.alwaysActive = object.alwaysActive ?? false;
    message.gestures = object.gestures?.map((e) => Gesture.fromPartial(e)) || [];
    message.activationKeys = object.activationKeys?.map((e) => ActivationKey.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListRequest(): ListRequest {
  return {};
}

export const ListRequest: MessageFns<ListRequest> = {
  encode(_: ListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListRequest>): ListRequest {
    return ListRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListRequest>): ListRequest {
    const message = createBaseListRequest();
    return message;
  },
};

function createBaseListResponse(): ListResponse {
  return { config: undefined };
}

export const ListResponse: MessageFns<ListResponse> = {
  encode(message: ListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListResponse>): ListResponse {
    return ListResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListResponse>): ListResponse {
    const message = createBaseListResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseSaveRequest(): SaveRequest {
  return { config: undefined };
}

export const SaveRequest: MessageFns<SaveRequest> = {
  encode(message: SaveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SaveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSaveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SaveRequest>): SaveRequest {
    return SaveRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SaveRequest>): SaveRequest {
    const message = createBaseSaveRequest();
    message.config = (object.config !== undefined && object.config !== null)
      ? Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseSaveResponse(): SaveResponse {
  return {};
}

export const SaveResponse: MessageFns<SaveResponse> = {
  encode(_: SaveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SaveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSaveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SaveResponse>): SaveResponse {
    return SaveResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SaveResponse>): SaveResponse {
    const message = createBaseSaveResponse();
    return message;
  },
};

function createBaseResetRequest(): ResetRequest {
  return {};
}

export const ResetRequest: MessageFns<ResetRequest> = {
  encode(_: ResetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetRequest>): ResetRequest {
    return ResetRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ResetRequest>): ResetRequest {
    const message = createBaseResetRequest();
    return message;
  },
};

function createBaseResetResponse(): ResetResponse {
  return { config: undefined };
}

export const ResetResponse: MessageFns<ResetResponse> = {
  encode(message: ResetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetResponse>): ResetResponse {
    return ResetResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResetResponse>): ResetResponse {
    const message = createBaseResetResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseRequest(): Request {
  return { list: undefined, save: undefined, reset: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.list !== undefined) {
      ListRequest.encode(message.list, writer.uint32(10).fork()).join();
    }
    if (message.save !== undefined) {
      SaveRequest.encode(message.save, writer.uint32(18).fork()).join();
    }
    if (message.reset !== undefined) {
      ResetRequest.encode(message.reset, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.list = ListRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.save = SaveRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reset = ResetRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.list = (object.list !== undefined && object.list !== null)
      ? ListRequest.fromPartial(object.list)
      : undefined;
    message.save = (object.save !== undefined && object.save !== null)
      ? SaveRequest.fromPartial(object.save)
      : undefined;
    message.reset = (object.reset !== undefined && object.reset !== null)
      ? ResetRequest.fromPartial(object.reset)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { list: undefined, save: undefined, reset: undefined, error: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.list !== undefined) {
      ListResponse.encode(message.list, writer.uint32(10).fork()).join();
    }
    if (message.save !== undefined) {
      SaveResponse.encode(message.save, writer.uint32(18).fork()).join();
    }
    if (message.reset !== undefined) {
      ResetResponse.encode(message.reset, writer.uint32(26).fork()).join();
    }
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.list = ListResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.save = SaveResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reset = ResetResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.list = (object.list !== undefined && object.list !== null)
      ? ListResponse.fromPartial(object.list)
      : undefined;
    message.save = (object.save !== undefined && object.save !== null)
      ? SaveResponse.fromPartial(object.save)
      : undefined;
    message.reset = (object.reset !== undefined && object.reset !== null)
      ? ResetResponse.fromPartial(object.reset)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
